# Linting configuration for deltakit_explorer.
#
# General and format configurations are repository-wide for the moment.
extend = "../ruff.toml"

[lint]
ignore = [
    "B",       # many manual adjustments required
    "E501",    # line length > 88 (fix later)
    "N",       # manual adjustment required
    "PLR2004", # magic values, especially in tests
    "PLR0912",
    "PLR0913",
    "PLR0915", # too many branches, arguments, statements
    "PLW1641", # Object does not implement `__hash__` method (fix later)
    "PLW2901", # Outer `for` loop variable `i` overwritten (fix later)
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"__init__.py" = ["F401"]
