name: Label PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  # Get changed labels
  label-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - id: label-PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
