name: Run pytest on all packages
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        package: ["deltakit-explorer", "deltakit-circuit", "deltakit-core", "deltakit-decode"]

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
              pyproject.toml
              deltakit-explorer/pyproject.toml
              deltakit-circuit/pyproject.toml
              deltakit-core/pyproject.toml
              deltakit-decode/pyproject.toml

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install ${{ matrix.package }} with test dependencies
        run: |
          # this currently needs to install all base dependencies declared in pyproject.toml
          pip install ".[tests]" ./deltakit-core ./deltakit-circuit ./deltakit-decode ./deltakit-explorer

      - name: Run ${{ matrix.package }} tests
        run: |
          pytest ${{ matrix.package }}
